[package]
name = "aelys-air"
version.workspace = true
edition = "2024"

[dependencies]
aelys-sema = { path = "../sema" }
aelys-syntax = { path = "../syntax" }

[dev-dependencies]
aelys-frontend = { path = "../frontend" }

[lib]
doctest = false
