[package]
name = "aelys-opt"
version.workspace = true
edition = "2024"

[dependencies]
aelys-common = { path = "../aelys-common" }
aelys-syntax = { path = "../aelys-syntax" }
aelys-sema = { path = "../aelys-sema" }
