[package]
name = "aelys-native-opengl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aelys-native = { path = "../../../../aelys-native" }
minifb = "0.27"

[workspace]
